// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat/plan/{mealPlanId}": {
            "post": {
                "description": "Handle general chat request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Handle general chat request",
                "operationId": "generalChat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal plan ID",
                        "name": "mealPlanId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "General chat request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GeneralChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GeneralChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/plan/{mealPlanId}/recipe": {
            "post": {
                "description": "Handle recipe suggestion chat request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Handle recipe suggestion chat request",
                "operationId": "suggestRecipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal plan ID",
                        "name": "mealPlanId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Suggest chat request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SuggestChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuggestChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/plan/{mealPlanId}/recipe/{recipeId}": {
            "put": {
                "description": "Handle recipe modification chat request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Handle recipe modification chat request",
                "operationId": "modifyRecipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal plan ID",
                        "name": "mealPlanId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Recipe ID",
                        "name": "recipeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Modify chat request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ModifyChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ModifyChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/meal/plan": {
            "post": {
                "description": "Create new meal plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal"
                ],
                "summary": "Create new meal plan",
                "operationId": "createMealPlan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MealPlan"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/meal/plan/{meal_plan_id}": {
            "get": {
                "description": "Get meal plan by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal"
                ],
                "summary": "Get meal plan by ID",
                "operationId": "getMealPlan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal plan ID",
                        "name": "meal_plan_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MealPlan"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "description": "Gets the profile for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user profile",
                "operationId": "getProfile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Profile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Save a user's profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Save user profile",
                "operationId": "saveProfile",
                "parameters": [
                    {
                        "description": "User profile",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProfileUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Profile"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.UnauthorizedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "description": "Register a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user account",
                "operationId": "signup",
                "parameters": [
                    {
                        "description": "User signup information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SignupResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Allergy": {
            "type": "string",
            "enum": [
                "dairy",
                "eggs",
                "fish",
                "gluten",
                "peanuts",
                "soy",
                "tree_nuts",
                "wheat"
            ],
            "x-enum-varnames": [
                "AllergyDairy",
                "AllergyEggs",
                "AllergyFish",
                "AllergyGluten",
                "AllergyPeanuts",
                "AllergySoy",
                "AllergyTreeNuts",
                "AllergyWheat"
            ]
        },
        "models.BadRequestResponse": {
            "description": "Bad request error response",
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "description": "Error message",
                    "type": "string",
                    "example": "Invalid input"
                }
            }
        },
        "models.Cuisine": {
            "type": "string",
            "enum": [
                "american",
                "british",
                "chinese",
                "french",
                "german",
                "indian",
                "italian",
                "japanese",
                "mexican",
                "spanish",
                "thai",
                "vietnamese"
            ],
            "x-enum-varnames": [
                "CuisineAmerican",
                "CuisineBritish",
                "CuisineChinese",
                "CuisineFrench",
                "CuisineGerman",
                "CuisineIndian",
                "CuisineItalian",
                "CuisineJapanese",
                "CuisineMexican",
                "CuisineSpanish",
                "CuisineThai",
                "CuisineVietnamese"
            ]
        },
        "models.Diet": {
            "type": "string",
            "enum": [
                "vegetarian",
                "vegan",
                "keto",
                "paleo",
                "low_carb",
                "high_protein"
            ],
            "x-enum-varnames": [
                "DietVegetarian",
                "DietVegan",
                "DietKeto",
                "DietPaleo",
                "DietLowCarb",
                "DietHighProtein"
            ]
        },
        "models.Equipment": {
            "type": "string",
            "enum": [
                "stove",
                "oven",
                "microwave",
                "toaster",
                "grill",
                "smoker",
                "slow_cooker",
                "pressure_cooker",
                "sous_vide"
            ],
            "x-enum-varnames": [
                "EquipmentStove",
                "EquipmentOven",
                "EquipmentMicrowave",
                "EquipmentToaster",
                "EquipmentGrill",
                "EquipmentSmoker",
                "EquipmentSlowCooker",
                "EquipmentPressureCooker",
                "EquipmentSousVide"
            ]
        },
        "models.GeneralChatRequest": {
            "description": "A chat request to the ML backend to answer a question",
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.GeneralChatResponse": {
            "description": "A chat response to the ML backend to answer a question",
            "type": "object",
            "required": [
                "response_text"
            ],
            "properties": {
                "response_text": {
                    "type": "string"
                }
            }
        },
        "models.Ingredient": {
            "type": "object",
            "required": [
                "name",
                "quantity",
                "unit"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Flour"
                },
                "quantity": {
                    "type": "number",
                    "example": 1
                },
                "unit": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeasurementUnit"
                        }
                    ],
                    "example": "cup"
                }
            }
        },
        "models.InternalServerErrorResponse": {
            "description": "Internal server error response",
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "description": "Error message",
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "models.MealPlan": {
            "description": "A meal plan",
            "type": "object",
            "required": [
                "id",
                "recipes",
                "user_id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "12345678-1234-1234-1234-123456789012"
                },
                "recipes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Recipe"
                    }
                },
                "user_id": {
                    "type": "string",
                    "example": "12345678-1234-1234-1234-123456789012"
                }
            }
        },
        "models.MeasurementUnit": {
            "type": "string",
            "enum": [
                "g",
                "ml",
                "tsp",
                "tbsp",
                "cup",
                "oz",
                "lb"
            ],
            "x-enum-varnames": [
                "MeasurementUnitGram",
                "MeasurementUnitMilliliter",
                "MeasurementUnitTeaspoon",
                "MeasurementUnitTablespoon",
                "MeasurementUnitCup",
                "MeasurementUnitOunce",
                "MeasurementUnitPound"
            ]
        },
        "models.ModifyChatRequest": {
            "description": "A chat request to the ML backend to modify a recipe",
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ModifyChatResponse": {
            "description": "A chat response to the ML backend to modify a recipe",
            "type": "object",
            "required": [
                "response_text"
            ],
            "properties": {
                "needs_clarification": {
                    "type": "boolean"
                },
                "new_recipe": {
                    "$ref": "#/definitions/models.Recipe"
                },
                "response_text": {
                    "type": "string"
                }
            }
        },
        "models.Profile": {
            "description": "User profile information",
            "type": "object",
            "required": [
                "allergies",
                "cuisines",
                "diet",
                "equipment",
                "name",
                "setup_step",
                "skill"
            ],
            "properties": {
                "allergies": {
                    "description": "User's allergies",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Allergy"
                    }
                },
                "cuisines": {
                    "description": "User's cuisines",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Cuisine"
                    }
                },
                "diet": {
                    "description": "User's diet restrictions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Diet"
                    }
                },
                "equipment": {
                    "description": "User's equipment",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Equipment"
                    }
                },
                "name": {
                    "description": "User's name",
                    "type": "string"
                },
                "setup_step": {
                    "description": "Setup Step",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SetupStep"
                        }
                    ]
                },
                "skill": {
                    "description": "User's skill level",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Skill"
                        }
                    ]
                }
            }
        },
        "models.ProfileUpdateRequest": {
            "description": "User profile update request",
            "type": "object",
            "required": [
                "setup_step"
            ],
            "properties": {
                "allergies": {
                    "description": "User's allergies",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Allergy"
                    }
                },
                "cuisines": {
                    "description": "User's cuisines",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Cuisine"
                    }
                },
                "diet": {
                    "description": "User's diet restrictions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Diet"
                    }
                },
                "equipment": {
                    "description": "User's equipment",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Equipment"
                    }
                },
                "name": {
                    "description": "User's name",
                    "type": "string"
                },
                "setup_step": {
                    "description": "Setup Step",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SetupStep"
                        }
                    ]
                },
                "skill": {
                    "description": "User's skill level",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Skill"
                        }
                    ]
                }
            }
        },
        "models.Recipe": {
            "description": "A recipe",
            "type": "object",
            "required": [
                "description",
                "id",
                "ingredients",
                "servings",
                "steps",
                "title",
                "total_time_minutes"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "A classic Italian dish"
                },
                "id": {
                    "type": "string",
                    "example": "12345678-1234-1234-1234-123456789012"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Ingredient"
                    }
                },
                "servings": {
                    "type": "integer",
                    "example": 4
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Veal Bolognese"
                },
                "total_time_minutes": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "models.SetupStep": {
            "type": "string",
            "enum": [
                "profile",
                "skill",
                "cuisines",
                "diet",
                "equipment",
                "allergies",
                "done"
            ],
            "x-enum-varnames": [
                "SetupStepProfile",
                "SetupStepSkill",
                "SetupStepCuisines",
                "SetupStepDiet",
                "SetupStepEquipment",
                "SetupStepAllergies",
                "SetupStepDone"
            ]
        },
        "models.SignupRequest": {
            "description": "User signup request",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "User's email address",
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "password": {
                    "description": "User's password",
                    "type": "string",
                    "example": "Password123!"
                }
            }
        },
        "models.SignupResponse": {
            "description": "User signup response containing the new user's ID",
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "description": "Access token for user",
                    "type": "string",
                    "example": "\u003cJWT_TOKEN\u003e"
                }
            }
        },
        "models.Skill": {
            "type": "string",
            "enum": [
                "beginner",
                "intermediate",
                "advanced",
                "chef"
            ],
            "x-enum-varnames": [
                "SkillBeginner",
                "SkillIntermediate",
                "SkillAdvanced",
                "SkillChef"
            ]
        },
        "models.SuggestChatRequest": {
            "description": "A chat request to the ML backend to suggest a recipe",
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.SuggestChatResponse": {
            "description": "A chat response to the ML backend to suggest a recipe",
            "type": "object",
            "required": [
                "response_text"
            ],
            "properties": {
                "new_recipe": {
                    "$ref": "#/definitions/models.Recipe"
                },
                "response_text": {
                    "type": "string"
                }
            }
        },
        "models.UnauthorizedResponse": {
            "description": "Unauthorized error response",
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "description": "Error message",
                    "type": "string",
                    "example": "Unauthorized"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EatMe API",
	Description:      "API for the EatMe recipe generation service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
