basePath: /
definitions:
  models.Allergy:
    enum:
    - dairy
    - eggs
    - fish
    - gluten
    - peanuts
    - soy
    - tree_nuts
    - wheat
    type: string
    x-enum-varnames:
    - AllergyDairy
    - AllergyEggs
    - AllergyFish
    - AllergyGluten
    - AllergyPeanuts
    - AllergySoy
    - AllergyTreeNuts
    - AllergyWheat
  models.BadRequestResponse:
    description: Bad request error response
    properties:
      error:
        description: Error message
        example: Invalid input
        type: string
    required:
    - error
    type: object
  models.Cuisine:
    enum:
    - american
    - british
    - chinese
    - french
    - german
    - indian
    - italian
    - japanese
    - mexican
    - spanish
    - thai
    - vietnamese
    type: string
    x-enum-varnames:
    - CuisineAmerican
    - CuisineBritish
    - CuisineChinese
    - CuisineFrench
    - CuisineGerman
    - CuisineIndian
    - CuisineItalian
    - CuisineJapanese
    - CuisineMexican
    - CuisineSpanish
    - CuisineThai
    - CuisineVietnamese
  models.Diet:
    enum:
    - vegetarian
    - vegan
    - keto
    - paleo
    - low_carb
    - high_protein
    type: string
    x-enum-varnames:
    - DietVegetarian
    - DietVegan
    - DietKeto
    - DietPaleo
    - DietLowCarb
    - DietHighProtein
  models.Equipment:
    enum:
    - stove
    - oven
    - microwave
    - toaster
    - grill
    - smoker
    - slow_cooker
    - pressure_cooker
    - sous_vide
    type: string
    x-enum-varnames:
    - EquipmentStove
    - EquipmentOven
    - EquipmentMicrowave
    - EquipmentToaster
    - EquipmentGrill
    - EquipmentSmoker
    - EquipmentSlowCooker
    - EquipmentPressureCooker
    - EquipmentSousVide
  models.GeneralChatRequest:
    description: A chat request to the ML backend to answer a question
    properties:
      message:
        type: string
    required:
    - message
    type: object
  models.GeneralChatResponse:
    description: A chat response to the ML backend to answer a question
    properties:
      response_text:
        type: string
    required:
    - response_text
    type: object
  models.Ingredient:
    properties:
      name:
        example: Flour
        type: string
      quantity:
        example: 1
        type: number
      unit:
        allOf:
        - $ref: '#/definitions/models.MeasurementUnit'
        example: cup
    required:
    - name
    - quantity
    - unit
    type: object
  models.InternalServerErrorResponse:
    description: Internal server error response
    properties:
      error:
        description: Error message
        example: Internal server error
        type: string
    required:
    - error
    type: object
  models.MealPlan:
    description: A meal plan
    properties:
      id:
        example: 12345678-1234-1234-1234-123456789012
        type: string
      recipes:
        items:
          $ref: '#/definitions/models.Recipe'
        type: array
      user_id:
        example: 12345678-1234-1234-1234-123456789012
        type: string
    required:
    - id
    - recipes
    - user_id
    type: object
  models.MeasurementUnit:
    enum:
    - g
    - ml
    - tsp
    - tbsp
    - cup
    - oz
    - lb
    type: string
    x-enum-varnames:
    - MeasurementUnitGram
    - MeasurementUnitMilliliter
    - MeasurementUnitTeaspoon
    - MeasurementUnitTablespoon
    - MeasurementUnitCup
    - MeasurementUnitOunce
    - MeasurementUnitPound
  models.ModifyChatRequest:
    description: A chat request to the ML backend to modify a recipe
    properties:
      message:
        type: string
    required:
    - message
    type: object
  models.ModifyChatResponse:
    description: A chat response to the ML backend to modify a recipe
    properties:
      needs_clarification:
        type: boolean
      new_recipe:
        $ref: '#/definitions/models.Recipe'
      response_text:
        type: string
    required:
    - response_text
    type: object
  models.Profile:
    description: User profile information
    properties:
      allergies:
        description: User's allergies
        items:
          $ref: '#/definitions/models.Allergy'
        type: array
      cuisines:
        description: User's cuisines
        items:
          $ref: '#/definitions/models.Cuisine'
        type: array
      diet:
        description: User's diet restrictions
        items:
          $ref: '#/definitions/models.Diet'
        type: array
      equipment:
        description: User's equipment
        items:
          $ref: '#/definitions/models.Equipment'
        type: array
      name:
        description: User's name
        type: string
      setup_step:
        allOf:
        - $ref: '#/definitions/models.SetupStep'
        description: Setup Step
      skill:
        allOf:
        - $ref: '#/definitions/models.Skill'
        description: User's skill level
    required:
    - allergies
    - cuisines
    - diet
    - equipment
    - name
    - setup_step
    - skill
    type: object
  models.ProfileUpdateRequest:
    description: User profile update request
    properties:
      allergies:
        description: User's allergies
        items:
          $ref: '#/definitions/models.Allergy'
        type: array
      cuisines:
        description: User's cuisines
        items:
          $ref: '#/definitions/models.Cuisine'
        type: array
      diet:
        description: User's diet restrictions
        items:
          $ref: '#/definitions/models.Diet'
        type: array
      equipment:
        description: User's equipment
        items:
          $ref: '#/definitions/models.Equipment'
        type: array
      name:
        description: User's name
        type: string
      setup_step:
        allOf:
        - $ref: '#/definitions/models.SetupStep'
        description: Setup Step
      skill:
        allOf:
        - $ref: '#/definitions/models.Skill'
        description: User's skill level
    required:
    - setup_step
    type: object
  models.Recipe:
    description: A recipe
    properties:
      description:
        example: A classic Italian dish
        type: string
      id:
        example: 12345678-1234-1234-1234-123456789012
        type: string
      ingredients:
        items:
          $ref: '#/definitions/models.Ingredient'
        type: array
      servings:
        example: 4
        type: integer
      steps:
        items:
          type: string
        type: array
      title:
        example: Veal Bolognese
        type: string
      total_time_minutes:
        example: 120
        type: integer
    required:
    - description
    - id
    - ingredients
    - servings
    - steps
    - title
    - total_time_minutes
    type: object
  models.SetupStep:
    enum:
    - profile
    - skill
    - cuisines
    - diet
    - equipment
    - allergies
    - done
    type: string
    x-enum-varnames:
    - SetupStepProfile
    - SetupStepSkill
    - SetupStepCuisines
    - SetupStepDiet
    - SetupStepEquipment
    - SetupStepAllergies
    - SetupStepDone
  models.SignupRequest:
    description: User signup request
    properties:
      email:
        description: User's email address
        example: john.doe@example.com
        type: string
      password:
        description: User's password
        example: Password123!
        type: string
    required:
    - email
    - password
    type: object
  models.SignupResponse:
    description: User signup response containing the new user's ID
    properties:
      token:
        description: Access token for user
        example: <JWT_TOKEN>
        type: string
    required:
    - token
    type: object
  models.Skill:
    enum:
    - beginner
    - intermediate
    - advanced
    - chef
    type: string
    x-enum-varnames:
    - SkillBeginner
    - SkillIntermediate
    - SkillAdvanced
    - SkillChef
  models.SuggestChatRequest:
    description: A chat request to the ML backend to suggest a recipe
    properties:
      message:
        type: string
    required:
    - message
    type: object
  models.SuggestChatResponse:
    description: A chat response to the ML backend to suggest a recipe
    properties:
      new_recipe:
        $ref: '#/definitions/models.Recipe'
      response_text:
        type: string
    required:
    - response_text
    type: object
  models.UnauthorizedResponse:
    description: Unauthorized error response
    properties:
      error:
        description: Error message
        example: Unauthorized
        type: string
    required:
    - error
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for the EatMe recipe generation service
  title: EatMe API
  version: "1.0"
paths:
  /chat/plan/{mealPlanId}:
    post:
      consumes:
      - application/json
      description: Handle general chat request
      operationId: generalChat
      parameters:
      - description: Meal plan ID
        in: path
        name: mealPlanId
        required: true
        type: string
      - description: General chat request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.GeneralChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GeneralChatResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Handle general chat request
      tags:
      - Chat
  /chat/plan/{mealPlanId}/recipe:
    post:
      consumes:
      - application/json
      description: Handle recipe suggestion chat request
      operationId: suggestRecipe
      parameters:
      - description: Meal plan ID
        in: path
        name: mealPlanId
        required: true
        type: string
      - description: Suggest chat request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SuggestChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuggestChatResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Handle recipe suggestion chat request
      tags:
      - Chat
  /chat/plan/{mealPlanId}/recipe/{recipeId}:
    put:
      consumes:
      - application/json
      description: Handle recipe modification chat request
      operationId: modifyRecipe
      parameters:
      - description: Meal plan ID
        in: path
        name: mealPlanId
        required: true
        type: string
      - description: Recipe ID
        in: path
        name: recipeId
        required: true
        type: string
      - description: Modify chat request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ModifyChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ModifyChatResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Handle recipe modification chat request
      tags:
      - Chat
  /meal/plan:
    post:
      consumes:
      - application/json
      description: Create new meal plan
      operationId: createMealPlan
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MealPlan'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Create new meal plan
      tags:
      - Meal
  /meal/plan/{meal_plan_id}:
    get:
      consumes:
      - application/json
      description: Get meal plan by ID
      operationId: getMealPlan
      parameters:
      - description: Meal plan ID
        in: path
        name: meal_plan_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MealPlan'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Get meal plan by ID
      tags:
      - Meal
  /meal/plans:
    get:
      consumes:
      - application/json
      description: Get all meal plans for user
      operationId: getAllMealPlans
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.MealPlan'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Get all meal plans for user
      tags:
      - Meal
  /profile:
    get:
      description: Gets the profile for a user
      operationId: getProfile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Profile'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Get user profile
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Save a user's profile
      operationId: saveProfile
      parameters:
      - description: User profile
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/models.ProfileUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Profile'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Save user profile
      tags:
      - users
  /signup:
    post:
      consumes:
      - application/json
      description: Register a new user account
      operationId: signup
      parameters:
      - description: User signup information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SignupResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Create a new user account
      tags:
      - users
swagger: "2.0"
