basePath: /
definitions:
  models.Allergy:
    enum:
    - dairy
    - eggs
    - fish
    - gluten
    - peanuts
    - soy
    - tree_nuts
    - wheat
    type: string
    x-enum-varnames:
    - AllergyDairy
    - AllergyEggs
    - AllergyFish
    - AllergyGluten
    - AllergyPeanuts
    - AllergySoy
    - AllergyTreeNuts
    - AllergyWheat
  models.BadRequestResponse:
    description: Bad request error response
    properties:
      error:
        description: Error message
        example: Invalid input
        type: string
    required:
    - error
    type: object
  models.ChatRequest:
    description: A chat request
    properties:
      meal_plan_id:
        type: string
      message:
        type: string
    required:
    - meal_plan_id
    - message
    type: object
  models.ChatResponse:
    description: A chat response
    properties:
      intent:
        type: string
      needs_clarification:
        type: boolean
      new_meal_plan:
        $ref: '#/definitions/models.MealPlan'
      response_text:
        type: string
    required:
    - intent
    - response_text
    type: object
  models.Cuisine:
    enum:
    - american
    - british
    - chinese
    - french
    - german
    - indian
    - italian
    - japanese
    - mexican
    - spanish
    - thai
    - vietnamese
    type: string
    x-enum-varnames:
    - CuisineAmerican
    - CuisineBritish
    - CuisineChinese
    - CuisineFrench
    - CuisineGerman
    - CuisineIndian
    - CuisineItalian
    - CuisineJapanese
    - CuisineMexican
    - CuisineSpanish
    - CuisineThai
    - CuisineVietnamese
  models.Diet:
    enum:
    - vegetarian
    - vegan
    - keto
    - paleo
    - low_carb
    - high_protein
    type: string
    x-enum-varnames:
    - DietVegetarian
    - DietVegan
    - DietKeto
    - DietPaleo
    - DietLowCarb
    - DietHighProtein
  models.Equipment:
    enum:
    - stove
    - oven
    - microwave
    - toaster
    - grill
    - smoker
    - slow_cooker
    - pressure_cooker
    - sous_vide
    type: string
    x-enum-varnames:
    - EquipmentStove
    - EquipmentOven
    - EquipmentMicrowave
    - EquipmentToaster
    - EquipmentGrill
    - EquipmentSmoker
    - EquipmentSlowCooker
    - EquipmentPressureCooker
    - EquipmentSousVide
  models.Ingredient:
    properties:
      name:
        example: Flour
        type: string
      quantity:
        example: 1
        type: number
      unit:
        allOf:
        - $ref: '#/definitions/models.MeasurementUnit'
        example: cup
    required:
    - name
    - quantity
    - unit
    type: object
  models.InternalServerErrorResponse:
    description: Internal server error response
    properties:
      error:
        description: Error message
        example: Internal server error
        type: string
    required:
    - error
    type: object
  models.MealPlan:
    description: A meal plan
    properties:
      id:
        example: 12345678-1234-1234-1234-123456789012
        type: string
      recipes:
        items:
          $ref: '#/definitions/models.Recipe'
        type: array
    required:
    - id
    - recipes
    type: object
  models.MeasurementUnit:
    enum:
    - g
    - ml
    - tsp
    - tbsp
    - cup
    - oz
    - lb
    type: string
    x-enum-varnames:
    - MeasurementUnitGram
    - MeasurementUnitMilliliter
    - MeasurementUnitTeaspoon
    - MeasurementUnitTablespoon
    - MeasurementUnitCup
    - MeasurementUnitOunce
    - MeasurementUnitPound
  models.Profile:
    description: User profile information
    properties:
      allergies:
        description: User's allergies
        items:
          $ref: '#/definitions/models.Allergy'
        type: array
      cuisines:
        description: User's cuisines
        items:
          $ref: '#/definitions/models.Cuisine'
        type: array
      diet:
        description: User's diet restrictions
        items:
          $ref: '#/definitions/models.Diet'
        type: array
      equipment:
        description: User's equipment
        items:
          $ref: '#/definitions/models.Equipment'
        type: array
      name:
        description: User's name
        type: string
      setup_step:
        allOf:
        - $ref: '#/definitions/models.SetupStep'
        description: Setup Step
      skill:
        allOf:
        - $ref: '#/definitions/models.Skill'
        description: User's skill level
    required:
    - allergies
    - cuisines
    - diet
    - equipment
    - name
    - setup_step
    - skill
    type: object
  models.ProfileUpdateRequest:
    description: User profile update request
    properties:
      allergies:
        description: User's allergies
        items:
          $ref: '#/definitions/models.Allergy'
        type: array
      cuisines:
        description: User's cuisines
        items:
          $ref: '#/definitions/models.Cuisine'
        type: array
      diet:
        description: User's diet restrictions
        items:
          $ref: '#/definitions/models.Diet'
        type: array
      equipment:
        description: User's equipment
        items:
          $ref: '#/definitions/models.Equipment'
        type: array
      name:
        description: User's name
        type: string
      setup_step:
        allOf:
        - $ref: '#/definitions/models.SetupStep'
        description: Setup Step
      skill:
        allOf:
        - $ref: '#/definitions/models.Skill'
        description: User's skill level
    required:
    - setup_step
    type: object
  models.Recipe:
    description: A recipe
    properties:
      description:
        example: A classic Italian dish
        type: string
      id:
        example: 12345678-1234-1234-1234-123456789012
        type: string
      ingredients:
        items:
          $ref: '#/definitions/models.Ingredient'
        type: array
      servings:
        example: 4
        type: integer
      steps:
        items:
          type: string
        type: array
      title:
        example: Veal Bolognese
        type: string
      total_time_minutes:
        example: 120
        type: integer
    required:
    - description
    - id
    - ingredients
    - servings
    - steps
    - title
    - total_time_minutes
    type: object
  models.SetupStep:
    enum:
    - profile
    - skill
    - cuisines
    - diet
    - equipment
    - allergies
    - done
    type: string
    x-enum-varnames:
    - SetupStepProfile
    - SetupStepSkill
    - SetupStepCuisines
    - SetupStepDiet
    - SetupStepEquipment
    - SetupStepAllergies
    - SetupStepDone
  models.SignupRequest:
    description: User signup request
    properties:
      email:
        description: User's email address
        example: john.doe@example.com
        type: string
      password:
        description: User's password
        example: Password123!
        type: string
    required:
    - email
    - password
    type: object
  models.SignupResponse:
    description: User signup response containing the new user's ID
    properties:
      token:
        description: Access token for user
        example: <JWT_TOKEN>
        type: string
    required:
    - token
    type: object
  models.Skill:
    enum:
    - beginner
    - intermediate
    - advanced
    - chef
    type: string
    x-enum-varnames:
    - SkillBeginner
    - SkillIntermediate
    - SkillAdvanced
    - SkillChef
  models.UnauthorizedResponse:
    description: Unauthorized error response
    properties:
      error:
        description: Error message
        example: Unauthorized
        type: string
    required:
    - error
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for the EatMe recipe generation service
  title: EatMe API
  version: "1.0"
paths:
  /chat:
    post:
      consumes:
      - application/json
      description: Handle chat request
      operationId: chat
      parameters:
      - description: Chat request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ChatResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Handle chat request
      tags:
      - Chat
  /profile:
    get:
      description: Gets the profile for a user
      operationId: getProfile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Profile'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Get user profile
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Save a user's profile
      operationId: saveProfile
      parameters:
      - description: User profile
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/models.ProfileUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Profile'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Save user profile
      tags:
      - users
  /signup:
    post:
      consumes:
      - application/json
      description: Register a new user account
      operationId: signup
      parameters:
      - description: User signup information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SignupResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.InternalServerErrorResponse'
      summary: Create a new user account
      tags:
      - users
swagger: "2.0"
