root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init -g cmd/api/main.go && go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "docs"]
delay = 1000 # ms

[log]
time = true

[screen]
clear_on_rebuild = true
